#!/bin/sh

logger -p notice -t "hotplug.d" "ntpd: run because of $INTERFACE $ACTION"

[ "$ACTION" = "ifup" ] || exit 0

if [ "$INTERFACE" = "wan" -o "$INTERFACE" = "lan" ]; then
   /usr/sbin/ntpsetclock post once >/dev/null 2>&1 &
fi
