#!/bin/sh

#if in ft_mode, do not start!
ft_mode=`cat /proc/xiaoqiang/ft_mode`
if [ "$ft_mode" -ne "0" ]; then
    return 0
fi

[ "$ACTION" = "ifdown" ] && [ "$INTERFACE" = "wan" ] && {
    killall trmd 2>/dev/null
}

[ "$ACTION" = "ifup" ] && [ "$INTERFACE" = "wan" ] && {
    killall trmd 2>/dev/null
    sleep 2
    [ -f /usr/bin/trmd ] && /usr/bin/trmd -r 10 &
}
