#!/bin/sh /etc/rc.common

START=19

boot() {
	# Be silent on boot, firewall might be started by hotplug already,
	# so don't complain in syslog.
	fw3 -q start || true
}

start() {
	fw3 start
	/usr/sbin/firewall.webinitrdr start
}

stop() {
	fw3 flush
}

restart() {
	fw3 restart
}

reload() {
	fw3 reload
}
