#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=45

SWITCH="/proc/sys/net/ipv4/ipaccount/drop_pkt_rand_num"

start() {
        ft_mode=`cat /proc/xiaoqiang/ft_mode`
        [ "$ft_mode" = "1" ] || return 0
	[ -e "$SWITCH" ] && echo 0 > "$SWITCH"
	return 0
}

