#!/bin/sh /etc/rc.common

START=99

start() {

	flag=`uci get misc.boot.sched_boot -q`
	[ "$flag" = "1" ] || return 0

	uci set misc.boot.sched_boot=0
	uci commit

	#indicate this is a scheduled reboot.
	touch /tmp/flag_sched_reboot
	return 0
}

