#!/bin/sh /etc/rc.common
# Copyright (C) 2009-2012 OpenWrt.org

START=12
STOP=99

start() {
	ulimit -c unlimited
	echo -1000 > /proc/$$/oom_score_adj
	/usr/sbin/taskmonitorServer
	/usr/sbin/taskmonitorDaemon -p "/usr/sbin/taskmonitorServer" -b "/usr/sbin/taskmonitorServer"
	return 0
}

restart() {
	stop
	sleep 1
	start
	return $?
}

shutdown() {
	stop
	return $?
}

stop() {
	return $?
}
status() {
	echo "status"
	return $?
}
#
