#!/bin/sh /etc/rc.common

START=99


export PROCLINE="/usr/bin/wrsst"
export PROCFLAG="/usr/bin/wrsst"
export PROC_DEBUG_FLAG="on"
export OOM_FLAG=0

export EXTRA_HELP="	status	Status the service"
export EXTRA_COMMANDS="status"
export PROC_USE_CGROUP_PATH="/dev/cgroup/cpu/plugin/tasks"
export DELAY_FLAG=1

stop() {
	/usr/sbin/supervisord stop
	return $?
}
start() {
	/usr/sbin/supervisord start
	return $?
}
restart() {
	stop
	sleep 1
	start
	return $?
}
shutdown() {
	stop
	return $?
}
status() {
	/usr/sbin/supervisord status
	return $?
}
