#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=10
STOP=98

applog(){
	msg="$@"
	test -z "$msg" && return 0
	test -z "$APPLOGTAG" && APPLOGTAG="init.d/boot"
	/usr/bin/logger -t "${APPLOGTAG}[${$}]" "$msg"
	DATE="`date`"
	echo "$DATE ${APPLOGTAG}[${$}]: $msg" >> /dev/console 2>/dev/null
	return 0
}
pipelog(){
	local oneline
	while read oneline
	do
		applog "$oneline"
	done
}
#
system_config() {
	local cfg="$1"

	local hostname conloglevel timezone

	config_get hostname "$cfg" hostname 'OpenWrt'
	echo "$hostname" > /proc/sys/kernel/hostname

	config_get conloglevel "$cfg" conloglevel
	config_get buffersize "$cfg" buffersize
	[ -z "$conloglevel" -a -z "$buffersize" ] || dmesg ${conloglevel:+-n $conloglevel} ${buffersize:+-s $buffersize}
}

apply_uci_config() {
	sh -c '. /lib/functions.sh; include /lib/config; uci_apply_defaults'
}

start() {
	[ -f /proc/mounts ] || /sbin/mount_root
	[ -f /proc/jffs2_bbc ] && echo "S" > /proc/jffs2_bbc
	[ -f /proc/net/vlan/config ] && vconfig set_name_type DEV_PLUS_VID_NO_PAD

	mkdir -p /var/run
	mkdir -p /var/log
	mkdir -p /var/lock
	mkdir -p /var/state
	mkdir -p /tmp/.uci
	chmod 0700 /tmp/.uci
	touch /var/log/wtmp
	touch /var/log/lastlog
	touch /tmp/resolv.conf.auto
	ln -sf /tmp/resolv.conf.auto /tmp/resolv.conf
	grep -q debugfs /proc/filesystems && mount -t debugfs debugfs /sys/kernel/debug
	[ "$FAILSAFE" = "true" ] && touch /tmp/.failsafe

	echo "S10boot-check-2" >> /tmp/messages
	load_modules /etc/modules.d/*

	echo "S10boot-check-3" >> /tmp/messages
	[ ! -f /etc/config/wireless -o -z /etc/config/wireless ] && {
		rm -f /etc/config/wireless
		/sbin/wifi detect > /tmp/wireless.tmp

		[ -s /tmp/wireless.tmp ] && {
			cat /tmp/wireless.tmp > /etc/config/wireless
		}
		rm -f /tmp/wireless.tmp
	}

	apply_uci_config
	config_load system
	config_foreach system_config system

	echo "S10boot-check-4" >> /tmp/messages
	killall -q hotplug2
	[ -x /sbin/hotplug2 ] && /sbin/hotplug2 --override --persistent \
			--set-rules-file /etc/hotplug2.rules \
			--set-coldplug-cmd /sbin/udevtrigger \
			--max-children 1 >/dev/null 2>&1 &

	echo "S10boot-check-5" >> /tmp/messages
	# create /dev/root if it doesn't exist
	[ -e /dev/root -o -h /dev/root ] || {
		rootdev=$(awk 'BEGIN { RS=" "; FS="="; } $1 == "root" { print $2 }' < /proc/cmdline)
		[ -n "$rootdev" ] && ln -s "$rootdev" /dev/root
	}
	return 0
}

stop() {
	[ -x /sbin/klogd ] && service_stop /sbin/klogd
	[ -x /sbin/syslogd ] && service_stop /sbin/syslogd
	killall -q hotplug2
}
