#!/bin/sh /etc/rc.common

START=99
STOP=20

#export command line for /usr/sbin/supervisord
export PROCLINE="/usr/sbin/smartcontroller"

start() {
	/usr/sbin/supervisord start
	return $?
}

restart() {
	stop
	sleep 1
	start
	return $?
}

shutdown() {
	stop
	return $?
}

stop() {
	/usr/sbin/supervisord stop
	return $?
}

status() {
	/usr/sbin/supervisord status
	return $?
}
