#!/bin/sh /etc/rc.common

START=99
#STOP=99

#export command line for /usr/sbin/supervisord
export PROCLINE='/usr/sbin/xqbc 988'
#

export EXTRA_HELP="     status  Status the service"
export EXTRA_COMMANDS="status"

start() {
	local wifimode
	netmode=`uci -q -S get xiaoqiang.common.NETMODE`
	if [ "$netmode" != "wifiapmode" -a "$netmode" != "lanapmode" ]; then
		return 0
	fi
        /usr/sbin/supervisord start
        return $?
}

restart() {
        stop
        sleep 1
        start
        return $?
}

shutdown() {
        stop
        return $?
}

stop() {
        /usr/sbin/supervisord stop
        return $?
}
status() {
        /usr/sbin/supervisord status
        return $?
}
#
